version: '3.3'
services:
  frontend:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - 2_apps

networks:
  2_apps:
