version: '3.5'
services:
  frontend:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - frontend

networks:
  frontend:
    name: ${NETWORK_NAME}
